### ISSUE TITLE
[How To] Scan for available networks?

### ISSUE THREAD

**Issue by pranjal-joshi** [scientifichackers/flutter-wifi-connect#3]
Hello,
First of all, I couldn't find this package on pub.dev so please let me know dependency to be added in `pubspec.yaml` file.
Also, as I am new to Flutter, I could not able to understand how to **Scan nearby SSIDs** (Get a list) and then connect to one of them as per the user input.

A simple code snippet for scanning WiFi networks would be great!
Also Do I need to add permissions explicitly in `AndroidManifest.xml` file to get access of WIFI and Location services?

**Comment by ignertic** [comment]
You just have to get the package from git. Check out this stackoverflow question that can help you https://stackoverflow.com/questions/54022704/how-to-add-a-package-from-github-flutter
